spring.application.name=smart-campus

# MongoDB
spring.data.mongodb.uri=mongodb+srv://nkaveesha14_db_user:mEaygxm83mWMXq4s@cluster0.wbfrkpx.mongodb.net/smart-campus?retryWrites=true&w=majority&appName=Cluster0

# Server
server.port=8080

# JWT
jwt.secret=SmartCampusSecretKey2026VeryLongSecretKeyForJWTTokenGeneration
jwt.expiration=86400000

# File upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
file.upload-dir=uploads/profile-photos

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=dummy-google-id
spring.security.oauth2.client.registration.google.client-secret=dummy-google-secret
spring.security.oauth2.client.registration.google.scope=email,profile

# GitHub OAuth2
spring.security.oauth2.client.registration.github.client-id=dummy-github-id
spring.security.oauth2.client.registration.github.client-secret=dummy-github-secret
spring.security.oauth2.client.registration.github.scope=user:email

# Facebook OAuth2
spring.security.oauth2.client.registration.facebook.client-id=dummy-facebook-id
spring.security.oauth2.client.registration.facebook.client-secret=dummy-facebook-secret
spring.security.oauth2.client.registration.facebook.scope=email,public_profile

# Logging (optional - helps debug)
logging.level.com.smartcampus=DEBUG