spring.application.name=smart-campus

spring.data.mongodb.uri=mongodb+srv://nkaveesha14_db_user:mEaygxm83mWMXq4s@cluster0.wbfrkpx.mongodb.net/smart-campus?retryWrites=true&w=majority&appName=Cluster0

server.port=8081

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

file.upload-dir=uploads/tickets